az vm create `
    --resource-group '' `
    --name '' `
    --image '' `
    --admin-username '' `
    --admin-password '' `
    --size '' `
    --security-type TrustedLaunch `
    --os-disk-name '' `
    --storage-sku '' `
    --nics '' `
    --zone ''
